import jsPDF from 'jspdf'

export function generateComplianceReport(data) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  const addText = (text, size, x, opts) => {
    doc.setFontSize(size)
    if (opts && opts.bold) doc.setFont('helvetica', 'bold')
    else doc.setFont('helvetica', 'normal')
    if (opts && opts.color) doc.setTextColor(opts.color[0], opts.color[1], opts.color[2])
    else doc.setTextColor(0, 0, 0)
    const lines = doc.splitTextToSize(text, pageWidth - (x || 20) - 20)
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20 }
      doc.text(line, x || 20, y)
      y += size * 0.5
    })
  }

  const addLine = () => {
    doc.setDrawColor(200, 200, 200)
    doc.line(20, y, pageWidth - 20, y)
    y += 5
  }

  // Header
  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, pageWidth, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('EU AI Act Compliance Report', 20, 18)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Regulation (EU) 2024/1689', 20, 28)
  doc.setFontSize(8)
  doc.text('Generated: ' + new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), pageWidth - 20, 28, { align: 'right' })
  y = 50

  // Company Info
  addText('Company / Website', 12, 20, { bold: true })
  addText(data.url || data.system_name || 'N/A', 10, 20, {})
  addText('Report Date: ' + new Date().toLocaleDateString('en-GB'), 10, 20, {})
  y += 5
  addLine()

  // Executive Summary
  addText('1. Executive Summary', 14, 20, { bold: true })
  y += 3
  addText(data.summary || 'No summary available.', 10, 20, {})
  y += 5
  addLine()

  // Overall Score
  addText('2. Overall Compliance Score', 14, 20, { bold: true })
  y += 3
  const score = data.overall_score || 0
  const scoreColor = score >= 80 ? [34, 197, 94] : score >= 60 ? [234, 179, 8] : score >= 40 ? [249, 115, 22] : [239, 68, 68]
  doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2])
  doc.roundedRect(20, y, 60, 25, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(score + '/100', 25, y + 15)
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const riskLevel = (data.risk_level || 'unknown').toUpperCase()
  doc.text('Risk Level: ' + riskLevel, 90, y + 8)
  doc.text('Based on Articles 5, 6, 9-15, 27, 52, 72, 73', 90, y + 16)
  y += 35
  addLine()

  // Detailed Checks
  if (data.checks && data.checks.length > 0) {
    addText('3. Detailed Compliance Checks', 14, 20, { bold: true })
    y += 3
    data.checks.forEach((check, i) => {
      if (y > 250) { doc.addPage(); y = 20 }
      const statusColor = check.status === 'compliant' ? [34, 197, 94] : check.status === 'non-compliant' ? [239, 68, 68] : check.status === 'warning' ? [234, 179, 8] : [156, 163, 175]
      doc.setFillColor(statusColor[0], statusColor[1], statusColor[2])
      doc.roundedRect(20, y - 4, 4, 4, 1, 1, 'F')
      addText((check.name || 'Check ' + (i + 1)), 10, 28, { bold: true })
      addText(check.details || 'No details available.', 9, 28, {})
      addText('Status: ' + check.status, 8, 28, { color: statusColor })
      y += 3
    })
    addLine()
  }

  // Recommendations
  if (data.recommendations && data.recommendations.length > 0) {
    if (y > 220) { doc.addPage(); y = 20 }
    addText('4. Recommendations', 14, 20, { bold: true })
    y += 3
    data.recommendations.forEach((rec, i) => {
      if (y > 260) { doc.addPage(); y = 20 }
      addText((i + 1) + '. ' + rec, 10, 20, {})
      y += 2
    })
    addLine()
  }

  // Legal Disclaimer
  if (y > 240) { doc.addPage(); y = 20 }
  addText('5. Legal Disclaimer', 14, 20, { bold: true })
  y += 3
  addText('This report is generated by automated AI analysis and does not constitute legal advice. The assessment is based on publicly visible webpage content and may not reflect the full scope of the organization\'s AI systems. For a complete EU AI Act compliance assessment, consult a qualified legal professional. This report is provided for informational purposes only.', 9, 20, { color: [100, 100, 100] })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text('AI Act Compliance Platform | Page ' + i + ' of ' + pageCount, pageWidth / 2, 290, { align: 'center' })
    doc.text('Regulation (EU) 2024/1689 | Not legal advice', pageWidth / 2, 295, { align: 'center' })
  }

  return doc
}

export function downloadReport(data) {
  const doc = generateComplianceReport(data)
  const fileName = 'EU-AI-Act-Compliance-Report-' + new Date().toISOString().split('T')[0] + '.pdf'
  doc.save(fileName)
  return fileName
}
