'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

export default function AnnexIVDocs() {
  const router = useRouter()
  const [formData, setFormData] = useState({
    systemName: '',
    provider: '',
    version: '',
    description: '',
    intendedPurpose: '',
    capabilities: '',
    limitations: '',
    trainingData: '',
    testingData: '',
    riskMeasures: '',
    humanOversight: '',
    accuracy: '',
    robustness: ''
  })
  const [generated, setGenerated] = useState(false)

  const handleChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  const handleGenerate = () => {
    if (!formData.systemName.trim()) {
      alert('Please enter a system name')
      return
    }
    setGenerated(true)
  }

  const generateDoc = () => {
    return `TECHNICAL DOCUMENTATION
(Annex IV of Regulation (EU) 2024/1689)

1. GENERAL DESCRIPTION
System Name: ${formData.systemName}
Provider: ${formData.provider}
Version: ${formData.version}

${formData.description}

2. INTENDED PURPOSE
${formData.intendedPurpose}

3. CAPABILITIES AND LIMITATIONS
Capabilities:
${formData.capabilities}

Limitations:
${formData.limitations}

4. DATA GOVERNANCE
Training Data:
${formData.trainingData}

Testing Data:
${formData.testingData}

5. RISK MANAGEMENT
Risk Mitigation Measures:
${formData.riskMeasures}

6. HUMAN OVERSIGHT
${formData.humanOversight}

7. PERFORMANCE METRICS
Accuracy: ${formData.accuracy}
Robustness: ${formData.robustness}

---
Generated by AI Act Compliance Tool
Date: ${new Date().toISOString().split('T')[0]}
`
  }

  const handleDownload = () => {
    const blob = new Blob([generateDoc()], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${formData.systemName}_Annex_IV.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <main className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-2">Annex IV Documentation</h1>
        <p className="text-gray-600 mb-8">Generate EU AI Act Annex IV Technical Documentation</p>
        
        <div className="space-y-4">
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">System Name *</label>
            <input type="text" value={formData.systemName} onChange={(e) => handleChange('systemName', e.target.value)}
              placeholder="Enter system name" className="w-full p-3 border rounded-lg" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Provider</label>
            <input type="text" value={formData.provider} onChange={(e) => handleChange('provider', e.target.value)}
              placeholder="Enter provider name" className="w-full p-3 border rounded-lg" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Version</label>
            <input type="text" value={formData.version} onChange={(e) => handleChange('version', e.target.value)}
              placeholder="e.g., 1.0.0" className="w-full p-3 border rounded-lg" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">System Description</label>
            <textarea value={formData.description} onChange={(e) => handleChange('description', e.target.value)}
              placeholder="Describe your AI system" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Intended Purpose</label>
            <textarea value={formData.intendedPurpose} onChange={(e) => handleChange('intendedPurpose', e.target.value)}
              placeholder="What is the intended purpose of this AI system?" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Capabilities</label>
            <textarea value={formData.capabilities} onChange={(e) => handleChange('capabilities', e.target.value)}
              placeholder="List the capabilities of the system" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Limitations</label>
            <textarea value={formData.limitations} onChange={(e) => handleChange('limitations', e.target.value)}
              placeholder="List known limitations" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Training Data Description</label>
            <textarea value={formData.trainingData} onChange={(e) => handleChange('trainingData', e.target.value)}
              placeholder="Describe the training data used" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Testing Data Description</label>
            <textarea value={formData.testingData} onChange={(e) => handleChange('testingData', e.target.value)}
              placeholder="Describe the testing/validation data" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Risk Mitigation Measures</label>
            <textarea value={formData.riskMeasures} onChange={(e) => handleChange('riskMeasures', e.target.value)}
              placeholder="Describe risk mitigation measures" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Human Oversight Measures</label>
            <textarea value={formData.humanOversight} onChange={(e) => handleChange('humanOversight', e.target.value)}
              placeholder="Describe human oversight measures" className="w-full p-3 border rounded-lg h-24" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Accuracy Metrics</label>
            <input type="text" value={formData.accuracy} onChange={(e) => handleChange('accuracy', e.target.value)}
              placeholder="e.g., 95% accuracy on test set" className="w-full p-3 border rounded-lg" />
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow">
            <label className="block text-sm font-medium mb-2">Robustness Metrics</label>
            <input type="text" value={formData.robustness} onChange={(e) => handleChange('robustness', e.target.value)}
              placeholder="e.g., Tested against adversarial attacks" className="w-full p-3 border rounded-lg" />
          </div>
        </div>
        
        <button onClick={handleGenerate}
          className="w-full mt-8 bg-blue-600 text-white py-4 rounded-lg text-lg font-medium hover:bg-blue-700">
          Generate Document
        </button>
        
        {generated && (
          <div className="mt-8 bg-white p-6 rounded-lg shadow">
            <h2 className="text-xl font-bold mb-4">Generated Document Preview</h2>
            <pre className="bg-gray-100 p-4 rounded-lg overflow-auto text-sm whitespace-pre-wrap">
              {generateDoc()}
            </pre>
            <button onClick={handleDownload}
              className="w-full mt-4 bg-green-600 text-white py-3 rounded-lg font-medium hover:bg-green-700">
              Download Document
            </button>
          </div>
        )}
        
        <button onClick={() => router.push('/dashboard')}
          className="w-full mt-4 bg-gray-200 text-gray-700 py-3 rounded-lg hover:bg-gray-300">Back to Dashboard</button>
      </div>
    </main>
  )
}
